<a href="https://colab.research.google.com/github/saamir16/MachineLearning/blob/main/IntroductiontoML/Class1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to NumPy
what we will cover?

creating arrays
multidimensional array
randomly generated arrays
element wise operations
summarizing operations

In [2]:
import numpy as np

In [4]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [8]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

Comparision


In [9]:
a>=2

array([False, False,  True,  True,  True])

In [10]:
a>b

array([False, False, False, False, False])

Summarizing of the data
Numpy provides function for summmarizing array data

In [13]:
a.std()

1.4142135623730951

In [15]:
a.min()

0

In [16]:
a.max()

4

In [17]:
a.sum()

10