<a href="https://colab.research.google.com/github/saamir16/MachineLearning/blob/main/IntroductiontoML/Class1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to NumPy**


What we will cover?

* Creating single dimensional arrays👌
* Multidimensional array👌
* Randomly generated arrays👌
* Element wise operations
* Summarizing operations

In [ ]:
import numpy as np

#Single dimensional arrays


In [ ]:
# Create an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Create an array with all the elements to be zeros
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Create an array of the size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create an array with evenly sapced numbers within a specifid range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multidimensional arrays


In [ ]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones([3,3])


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

In [ ]:
a[0,1] = 20
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
a[2] = [1, 1, 1]
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]


In [ ]:
a[:, 2] = [2, 2, 2]
a


array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
# Create an multidimensioanal array with all elements 10
np.full((3, 3),10)


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated arrays
* Numpy can create arrays filled with random numbers
* To ensure the reproducibility, you can seta sed using np.random.seed().It will generate the exact same random numbers for each executions.
* If you remove or change the seed values, the sequence of random numbers will be changed.



In [ ]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

Comparision


In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
a>b

array([False, False, False, False, False])

Summarizing of the data
Numpy provides function for summmarizing array data

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.min()

0

In [ ]:
a.max()

4

In [ ]:
a.sum()

10